### ISSUE TITLE
How to handle multiple PR's?

### ISSUE THREAD

**Issue by Adarsh-Suvarna** [mshick/add-pr-comment#103]
Hi Team,

I have doubt on how this works for multiple PR's? Suppose if I opened 4 PR's in my GitHub repo, in which PR the required message will be posted as a comment? Whether its latest PR or PR which is raised first?
Is it possible to mention PR number in the workflow so that I can post my comments in specific PR ?

**Comment by Adarsh-Suvarna** [comment]
Some variable like **pr_number** a number of the pull request where to create the comment is it available ?

**Comment by mshick** [comment]
If you are using the branch push trigger, then the branch being merged will be evaluated and if the action finds that there is an associated PR with that branch the message will be posted there. The order you merge in won't have any impact.

I'm assuming you're using a triggering event config that looks like below. 

```
on:
  push:
    branches:
      - main
```

There's also an [advanced use case](https://github.com/mshick/add-pr-comment#bring-your-own-issues) where you could specify an `issue` number to write to — in GitHub the conversation related to a PR is actually identified by an issue number.

Hopefully this addresses your question. If not feel free to re-open and provide more detail.
