### ISSUE TITLE
Upgrade action to use Node.js 20 to avoid Node.js 16 deprecation

### ISSUE THREAD

**Issue by benjmor** [mshick/add-pr-comment#113]
In Spring 2024, GHA will deprecate Node.js 16. In order for this action to keep running, it will need to upgrade.

For details: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

For an example of another Action's PR to migrate to Node.js 20: https://github.com/falti/dotenv-action/pull/51/files

**Comment by mshick** [comment]
All set. Thanks!
