### ISSUE TITLE
[PSA] No need for proxy for fork based PRs!

### ISSUE THREAD

**Issue by abhijitvalluri** [mshick/add-pr-comment#25]
Hi, I am not sure if this is a feature that was newly introduced in Github actions, but it is completely unnecessary to use a proxy based solution for PRs from forks.

All you need to do is replace the trigger "pull_request" to "pull_request_target". This will allow the workflow to access secrets. More info here: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target and I quote:

> This event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload. 

The only catch of this approach is that the workflow file used is the one already checked into the repo. So if you are creating a new workflow that uses secrets and want to test this in the PR that is checking in this file, it won't work because this file does not yet exist in the base repository. But once the PR is merged and the workflow file is in the base repo, subsequent PRs from forks will trigger the workflow properly.

This is a public service announcement of types so that others can use this and other actions that rely on secrets without using proxies and can still have them work for PRs from a fork!

**Comment by mahsadarabi66** [comment]
very very good :) 
[دلخوشی رضا صادقی](https://naslemusic.com/رضا-صادقی-دلخوشی.html) 
[ماکان بند](https://naslemusic.com/tag/دانلود-جدیدترین-آهنگ-ماکان-بند)

**Comment by mikob** [comment]
I haven't been able to get this working. I get  "Error: Not Found" which I think is due to permissions when I try this method. I have the GH token included, I have: "Send secrets to workflows from fork pull requests" and "Send write tokens to workflows from fork pull requests." on.

**Comment by mshick** [comment]
@abhijitvalluri Thanks for this. I'm going to leave proxy-url support in since there might be cases where that is preferable, but hopefully folks will find this info useful.
