### ISSUE TITLE
Feature Request: Cleanup Previous comments

### ISSUE THREAD

**Issue by ingshtrom** [mshick/add-pr-comment#28]
What are your thoughts on having the ability to clean up old comments? The problem would be that there are situations where multiple comments are made in the same workflow, as in matrix jobs, so we would need some sort of identifier, but I think we can achieve this through embedding this identifier within a comment `<!-- insert_identifier_here -->` within the comment it self. This would be a argument that the user needs to supply and it is their responsibility to ensure it is consistent and repeatable across action runs. 

I can take a shot at it, but was just curious on your thoughts on it.

**Comment by mjpost** [comment]
I came here to make the same request. We (https://github.com/acl-org/acl-anthology/) use this to post links to a preview site, with the message summarizing the differences between the preview and the master branch. These messages often vary by just a word or two, which means that the conversation history gets cluttered with many nearly-redundant comments.

**Comment by mshick** [comment]
@ingshtrom Thanks for the suggestion. I think that's a good idea and a good approach. I'll see if I can get it in soon.

**Comment by mshick** [comment]
@ingshtrom @mjpost Sorry for the long wait here. The action has been updated to use a comment identifier like you suggested. You can also configure that by setting `message-id`. This allows you to have multiple "sticky" or updated comments. The old approach of comparing text has been removed. Hopefully this works well for you. `@v2`-only.

**Comment by mshick** [comment]
And please comment back with any feedback or issues with the new features!

**Comment by mjpost** [comment]
Thanks! Testing this now.
