### ISSUE TITLE
File content as the message

### ISSUE THREAD

**Issue by ghost** [mshick/add-pr-comment#36]
I have the message prepared in the step and it is multyline. Unfortunately, github action output truncate multiline. I decided to write message to file, but it is not possible to print file right now.

Do you think it is good idea?

**Comment by apexearth** [comment]
I had a similar probablem and took an approach from this link to pass my multiline string as an output to the next step.

https://trstringer.com/github-actions-multiline-strings/

**Comment by pbrisbin** [comment]
This would still be useful for big messages. I have a case that can produce a large comment and it fails with

> Error: An error occurred trying to start process '/home/runner/runners/2.298.2/externals/node12/bin/node' with working directory '/home/runner/work/infra/infra'. Argument list too long

I think the comment body from a file would solve this. For example `create-release` accepts `body_path`.

**Comment by mshick** [comment]
@pbrisbin Interesting — I think I can get this in. Thanks for the pointer to create-release.

**Comment by pbrisbin** [comment]
I actually have it working in the fork on the freckle organization, though not sure how well it's implemented. If you want to use that as a reference. Thanks!

**Comment by mshick** [comment]
@pbrisbin @ghost Hopefully this works for you. If you have a chance to test and it's not working as expected please reopen this issue.
