### ISSUE TITLE
Update instead of duplicate

### ISSUE THREAD

**Issue by oreporan** [mshick/add-pr-comment#39]
Hey, nice github action!

I'm using it to write which packages in a monorepo have been affected. 

Is it possible to always edit the same message? without writing a new one. I see right now you compare the text, but I'd like to always update the existing message if exists. 

In my use case for example, you could run into this confusion:

`commit-1` changes package A
`commit-2` changes package A, package B
`commit-3` changes package A (reverts the package B change)

In the current flow, we won't print a new comment because you already find the comment after `commit-1`

I can make a PR + new config

**Comment by sammcj** [comment]
This would be really good, it's similar to what various test/coverage reporting Actions do, for example https://github.com/marketplace/actions/jest-coverage-report

**Comment by mshick** [comment]
@oreporan Great point. This might work with #28, using a message identifier rather than comparing the text. I should be able to get to it soon.

**Comment by mshick** [comment]
@oreporan @sammcj I've updated the action to behave this way. You can also now pass a `message-id` in case you want multiple "sticky" comments. The old approach of comparing text and / or a user email has been removed. This is only in `v2`. 

If you have a chance to test please let me know if it's working as you'd expect.
