### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by mattcanty** [mshick/add-pr-comment#43]
Hey, sorry to pick on you but I've been trying a whole bunch of commenting actions. Not one has worked. I am getting the following error and cannot get to the bottom of it:

https://github.com/mattcanty/dns/runs/5058217662?check_suite_focus=true#step:3:8

```
0s
Run mshick/add-pr-comment@v[1](https://github.com/mattcanty/dns/runs/5058217662?check_suite_focus=true#step:3:1)
  with:
    message: **Hello MASTER**
  
    allow-repeats: true
  env:
    GITHUB_TOKEN: ***
Error: Resource not accessible by integration
```

I end up on this page a lot, but it's not really telling me anything:
https://dev.to/callmekatootie/debug-resource-not-accessible-by-integration-error-when-working-with-githubs-graphql-endpoint-5bim

Am I meant to have a GitHub App set up for this to work?

**Comment by mattcanty** [comment]
OK figured it out but I find it a bit odd that not one Action seems to mention that `issues:write` must be stated in the job:

```yaml
jobs:
  deploy:
    name: Commenting
    runs-on: ubuntu-latest
    permissions:
      issues: write
...
```

Also something was definitely conspiring against me! In this commit I set the correct permission and the build fails:
https://github.com/mattcanty/dns/pull/4/commits/e8c962008fc51019d93ca936830fc8a7e2f84bab#diff-12408356b599c87378456ad7c9331f386ca486d7b9c6c13666b615033f10faefR13

Later on I retry it (definition of madness):
https://github.com/mattcanty/dns/pull/4/commits/e2a52fb46bf5222ae743ab0daac8fdf142971a93

Voila! It works.

Anyway, problem or no problem I close this ticket. Hope it will save someone a few hours one day.

**Comment by mattcanty** [comment]
Turns out, after a little more messing around (https://github.community/t/github-actions-pr-comment-permissions/227408) the correct permission is actually:

`pull-requests: true`

!!!

**Comment by Lissy93** [comment]
Hi @mattcanty 
Sorry to bother you, but I'm fully baffled by this, and you seem to be an expert.

Did you get this working for when non-contributors submit a pull request? Or just for pre-added team members.

I can't figure out if it's possible to have a comment added to pull requests added by new contributors...
but my [current workflow](https://github.com/Lissy93/awesome-privacy/blob/main/.github/workflows/validate-pr.yml) only runs successfully for existing maintainers

Any tips would be very much appreciated :)
