### ISSUE TITLE
GitHub Actions - set-output command is deprecated

### ISSUE THREAD

**Issue by ubaid-ansari21** [mshick/add-pr-comment#51]
Hey Team,

I was working with one of my GH workflow and found the below warning.

```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

Can we update action accordingly?

**Comment by mshick** [comment]
Handled in `v2`!
