### ISSUE TITLE
GitHubaction `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by donfirst** [mshick/add-pr-comment#54]
Describe the feature

The ::set-output:: function is deprecated in favor of using the GITHUB_OUTPUT environment file

Use Case

The set-output function is insecure according to this notification: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Other Information

No response

**Comment by mshick** [comment]
If you update to `v2` you should be good!

**Comment by donfirst** [comment]
V2 doesn't work  
Error: could not get message text, check your message-path
<img width="642" alt="image" src="https://user-images.githubusercontent.com/20359212/200284370-abeec5dd-de64-4dea-8cd7-1b96fe7cb7fd.png">
