### ISSUE TITLE
Inputs 'repo-token', and 'status' should not be required

### ISSUE THREAD

**Issue by edosrecki** [mshick/add-pr-comment#65]
These fields have default values and therefore users are not required to specify them. This causes errors in VS Code for example:

<img width="337" alt="Screenshot 2022-11-09 at 12 22 05" src="https://user-images.githubusercontent.com/26404168/200817592-52b99f02-bec6-4992-89cf-e06b5716dd14.png">

**Comment by mshick** [comment]
Thanks for reporting this! I've updated the definitions and bumped the release. Please let me know if you're still seeing issues.
