### ISSUE TITLE
Leading Whitespace is Trimmed

### ISSUE THREAD

**Issue by btruong66** [mshick/add-pr-comment#71]
Hello,

I'm using the add-pr-comment Github action to output lint fix results into my PRs comments. For example, a SQL after linting may look like the following:

```
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;
```

In my workflow I output the above into an intermediate file `results` and pass this `results` file to the `messagePath` for my `add-pr-comment` step. 

However the comment comes out as:
```
SELECT
FIRST_NAME,
LAST_NAME,
DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;
```

Which doesn't accurately reflect the results.

**Comment by mshick** [comment]
I think your issue might be in how you're adding the info to the comment. Since markdown is fully supported you'd want to put your pre-formatted / indented text in a codeblock — \`\`\`.

If putting it in a code block doesn't work perhaps you can share a reproduction with me?

**Comment by mshick** [comment]
Hi @btruong66 it looks like codeblocks are correctly preserving indents. Check out the [example here](https://github.com/mshick/add-pr-comment/blob/codeblock-test/.github/workflows/ci.yml#L90-L103) and the output here: https://github.com/mshick/add-pr-comment/pull/81#issuecomment-1518628028.

I will add a codeblock to the README just to make clear this is possible. 

Please let me know if you're able to make this work, and re-open if you're still finding issues with the indent.
