### ISSUE TITLE
[Feature] Allow `message-path` fallback if file not found

### ISSUE THREAD

**Issue by jpluscplusm** [mshick/add-pr-comment#75]
Hey there - thank you for this excellent Action!

I would like to ask for a fallback mechanism, where if the `message-path` file is missing, the contents of some configured key is used instead. Not /necessarily/ `message-failure` (as I can see the disadvantages of overloading its purpose), however using that field would seem to communicate the /intent/ here. 

### Rationale

I find myself most often configuring this Action via the `message-path` param; primarily for longer-form "result of the build/workflow" formatted comments.

However, when a build comprising several steps /fails/, in ways apart from "a test run completed, but with failures", 2 things happen:

1. I'm almost always left wanting to communicate this structural failure in some shorter-but-still-formatted message
1. The message-path file hasn't been created, due to the build/etc failure... failing!

Right now, to use this Action to cope with this situation, I need to arrange for a shell command step to run ahead of this Action, every time, to check if the message-path file exists; and, if it doesn't, dump my generic, short, formatted"Build failed" message in the file.

Then this Action can be activated unconditionally, with a definitely-existing file.

I /suspect/ I'm not alone in this flow, where I don't have a nice `step.<foo>.conclusion` way to identify, and communicate to the Action, that "the build failed". Where instead it's simply **the fact that the file is missing** which is the indicator of failure -- and I'm currently having to script around that scenario pretty frequently.

I would like to request that this Action remove that burden from me, the consumer, by "simply" adding a fallback, in cases where the `message-path` file is missing. ❤️

**Comment by mshick** [comment]
@jpluscplusm Great point and thanks for the detailed explanation. I agree, this would be useful. Looks like a PR has been offered by the community, I'll have a look and hopefully we can get that in soon.

**Comment by mshick** [comment]
@jpluscplusm I think this issue is resolved with `v2.6.1`. Please let me know if it now solves your use case.

**Comment by jpluscplusm** [comment]
@mshick Yes, thank you: I've validated that this change allows me to remove some complexity from my pipelines :-) 

I still find the README a tad confusing as to how it should work, at first and second glance, but I'll PR some changes that make it make more sense to me, and you can be the judge of that :-)
