### ISSUE TITLE
comment on a PR in another repo

### ISSUE THREAD

**Issue by ReenigneArcher** [mshick/add-pr-comment#77]
Is it possible to comment on a PR in another repo?

I have a somewhat complicated workflow. The workflow in one repo will trigger a workflow in another repo with a repository dispatch event. I want the triggered workflow to comment on the PR from the repo that triggered the repository dispatch event.

Any ideas?

**Comment by mshick** [comment]
Interesting idea, I can see the value, though I'm curious how you'd get the issue number for the other repo you want the comment in? The feature that finds the related PR works off the commit sha, which isn't going to be the same between two repos. 

I believe you can pass info as a dispatch payload, in which case you could pass the issue number there and use the `issue` override. Is that how you'd do things?

Happy to consider your PR, but I'd like a concrete scenario where this would work first so I can document it.

**Comment by ReenigneArcher** [comment]
I'm using "workflow_dispatch" to handle it, but you could also use "repository_dispatch"... the difference being that the "repository_dispatch" workflows have to be on the default branch, and I wanted the ability to call the workflow on any branch, so went with "workflow_dispatch".

Here's my dispatch workflow: https://github.com/LizardByte/.github/blob/nightly/.github/workflows/dispatch-issue-comment.yml

I use this action to call the workflow: https://github.com/benc-uk/workflow-dispatch

And create the inputs as json in bash using `jq`.
