### ISSUE TITLE
Add `update-only` configuration option to prevent initial creation of a comment in certain cases

### ISSUE THREAD

**Issue by ahatzz11** [mshick/add-pr-comment#87]
Hello!

I have a workflow where we have two actions that update the same comment. The first action posts a message saying a deployment was complete, and the second action posts a message saying the deployment was deleted. There's a case though where the deployment doesn't happen (e.g. only a README was changed and no deployment was created), but the 'deployment deleted' comment still gets made which is a bit misleading. 

Is there an option to say 'only update a comment that already exists' instead of creating one? I looked through the docs and nothing immediately jumped out at me so I thought I'd start an issue to discuss it. 

Thanks in advance!

**Comment by mshick** [comment]
@ahatzz11 That is not an option, but it sounds like a good one. Something like this, maybe?

```
- uses: mshick/add-pr-comment
  with:
    message-id: deployment
    update-only: true
```

**Comment by ahatzz11** [comment]
@mshick Yeah that would be perfect! I had a few random ideas for names but I think `update-only: true` is perfect 👍
