### ISSUE TITLE
allow-repeats doesn't work with ${{ ... }} parameters

### ISSUE THREAD

**Issue by JasonFreeberg** [mshick/add-pr-comment#9]
First of all, this is a great action and thank you for making it. I found a bug where the `allow_repeats` is set to false but I'm getting repeat comments on the PR. The `message` uses markdown and uses the `${{ github.event.number }}`. Maybe that's somehow causing the problem?

- Here is a repro: https://github.com/Azure/AppService/pull/100
- And here is the workflow: https://github.com/Azure/AppService/blob/master/.github/workflows/deploy-to-staging-site.yml

**Comment by JasonFreeberg** [comment]
I think the problem is [this line](https://github.com/mshick/add-pr-comment/blob/76803ee3439b66407174974f31f218ea1fbb4e7f/index.js#L71). It compares the message template to the comment. If the user has templating using the `${{ ... }}`, then the comparison will always fail.

**Comment by mshick** [comment]
@JasonFreeberg Glad you're finding it useful! 

I use the action for something very similar to yourself, and do not get repeated messages, so I know it works in some cases with GitHub interpolations present in the message. I'll dig in some more, but can you try removing `allow-repeats` entirely from your action and see if that helps? The default behavior is to disallow repeats.

**Comment by mshick** [comment]
Actually, I believe I found the issue — control characters like linebreaks appear to have been breaking the comparison, though I'm still not sure why it works for other multi-line strings.

Can you please try running the action using the `@master` version before I cut a release? Just replace `mshick/add-pr-comment@v1` with `mshick/add-pr-comment@master` in your workflow.

**Comment by JasonFreeberg** [comment]
@mshick Good thinking! I switched to `@master` and gave it a couple runs. Sadly there's no change. Might be worth saying that I'm on a Windows machine, so the line break characters may be different than Mac/Linux. 

PR: https://github.com/Azure/AppService/pull/98

**Comment by mshick** [comment]
I see, can you try one more time? I've added a pattern for Windows newlines as well.

**Comment by mshick** [comment]
@JasonFreeberg I've refactored the whole project to bring in typescript and unit tests (been meaning to do it). I set up a unit test for this case — windows linefeeds, unix-y API responses, and it passes so I think I've solved this. Would appreciate your confirmation that it works before I publish though.

**Comment by mshick** [comment]
I've released the updated version of this as v1. Feel free to reopen this issue if you still have problems.

**Comment by JasonFreeberg** [comment]
Hi @mshick, I just ran another test and it looks like it's still commenting duplicates.

https://github.com/Azure/AppService/pull/98#issuecomment-634228478

**Comment by mshick** [comment]
Oh man, that's a bummer! Let me try cloning your repo to see if I can isolate this issue. It looks like you're doing everything correctly there. Will report back ASAP.

**Comment by mshick** [comment]
@JasonFreeberg I figured it out! 

You appear to be using a personal access token `${{ secrets.GITHUB_ACCESS_TOKEN }}` rather than the temporary bot token, `${{ secrets.GITHUB_TOKEN }}` that GitHub provides. This means your comments are failing the check that first filters for comments by the `github-actions[bot]` user.

I'll investigate making this work with PATs, so you can have comments appear as coming from your user. In the meantime if you update your workflow to use the default bot token the repeats should stop.

**Comment by mshick** [comment]
Just landed a PR and re-released. Your workflow should stop repeating messages now with no changes, but I suggest reviewing the README quickly to see what has changed.

**Comment by JasonFreeberg** [comment]
Wow! Good catch @mshick and thanks for making it work with PATs!
