### ISSUE TITLE
v2 major tag didn't get updated for v2.4.0

### ISSUE THREAD

**Issue by ahatzz11** [mshick/add-pr-comment#95]
Hey @mshick! I appreciate the PR merge of #92 and the quick release of `v2.4.0`! This issue is to note that the [v2](https://github.com/mshick/add-pr-comment/releases/tag/v2) tag didn't seem to get an update. We reference action versions as major tags (like most actions recommend), and I'd love to get the latest release with this:

```
    - name: Add PR comment
      uses: mshick/add-pr-comment@v2
```

Thanks!

**Comment by mshick** [comment]
Ah, thanks, I've pushed that tag update now.
